import {
  authenticateCardIntelligenceSession,
  authenticateScanDatabaseSession,
  createUserScopedSupabaseClient,
} from "@miraio/db";
import {
  createRawScanImageExpiration,
  normalizeCardExtraction,
} from "@miraio/domain";
import { describe, expect, it } from "vitest";

import { processCardIntelligence } from "./card-intelligence";

const runIntegration = process.env.MIRAIO_RUN_SUPABASE_INTEGRATION === "1";

describe.runIf(runIntegration)("Card Intelligence Supabase integration", () => {
  it("extracts, persists, records Evidence, and deletes generated bytes", async () => {
    const url = process.env.SUPABASE_URL;
    const publishableKey = process.env.SUPABASE_PUBLISHABLE_KEY;
    const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!url || !publishableKey || !serviceRoleKey) {
      throw new Error("Local Supabase integration configuration is required.");
    }

    const email = `ml005-runtime-${crypto.randomUUID()}@miraio.invalid`;
    const password = `Miraio-${crypto.randomUUID()}!`;
    const createResponse = await fetch(`${url}/auth/v1/admin/users`, {
      body: JSON.stringify({ email, email_confirm: true, password }),
      headers: {
        apikey: serviceRoleKey,
        Authorization: `Bearer ${serviceRoleKey}`,
        "Content-Type": "application/json",
      },
      method: "POST",
    });

    expect(createResponse.status).toBe(200);
    const createdUser = (await createResponse.json()) as { id: string };

    try {
      const tokenResponse = await fetch(
        `${url}/auth/v1/token?grant_type=password`,
        {
          body: JSON.stringify({ email, password }),
          headers: {
            apikey: publishableKey,
            "Content-Type": "application/json",
          },
          method: "POST",
        },
      );
      expect(tokenResponse.status).toBe(200);
      const token = (await tokenResponse.json()) as { access_token: string };
      const config = { publishableKey, url };
      const scanSession = await authenticateScanDatabaseSession(
        config,
        token.access_token,
      );

      expect(scanSession).not.toBeNull();
      if (!scanSession) {
        return;
      }

      const scanId = crypto.randomUUID();
      const rawImagePath = `${createdUser.id}/${scanId}/front.jpg`;
      await scanSession.repository.reserve({
        expiresAt: createRawScanImageExpiration(new Date()),
        meetingGoal: "networking",
        rawImagePath,
        scanId,
      });
      await scanSession.repository.uploadRawImage(
        rawImagePath,
        new Uint8Array([255, 216, 255, 217]).buffer,
        "image/jpeg",
      );
      await scanSession.repository.completeUpload(scanId);

      const extraction = normalizeCardExtraction({
        address: null,
        company: "Runtime Invalid Labs",
        department: null,
        email: "runtime.card@example.invalid",
        field_confidence: {
          address: 0,
          company: 0.98,
          department: 0,
          email: 0.96,
          name: 0.99,
          phone: 0,
          title: 0.97,
          website: 0,
        },
        language: "en",
        name: "Runtime Testperson",
        phone: null,
        title: "Test Lead",
        website: null,
      });
      let now = 100;
      const result = await processCardIntelligence(
        { accessToken: token.access_token, scanId },
        {
          authenticate: (accessToken) =>
            authenticateCardIntelligenceSession(config, accessToken),
          createExtractor: () => ({
            async extract() {
              now = 142;
              return extraction;
            },
          }),
          modelAlias: "deterministic-fixture",
          nowMilliseconds: () => now,
          provider: "fixture",
        },
      );

      expect(result).toEqual({ rawImageDeleted: true, status: "completed" });

      const cardSession = await authenticateCardIntelligenceSession(
        config,
        token.access_token,
      );
      expect(cardSession).not.toBeNull();
      const status = await cardSession?.repository.getStatus(scanId);
      expect(status).toMatchObject({
        card: {
          company: "Runtime Invalid Labs",
          name: "Runtime Testperson",
          title: "Test Lead",
        },
        status: "card_ready",
      });

      const client = createUserScopedSupabaseClient(config, token.access_token);
      const [scanResult, evidenceResult, runResult] = await Promise.all([
        client
          .from("scans")
          .select("raw_image_path,status")
          .eq("id", scanId)
          .single(),
        client.from("evidence").select("source_type").eq("scan_id", scanId),
        client
          .from("ai_runs")
          .select("status,latency_ms")
          .eq("scan_id", scanId)
          .single(),
      ]);

      expect(scanResult.data).toEqual({
        raw_image_path: null,
        status: "card_ready",
      });
      expect(evidenceResult.data).toHaveLength(4);
      expect(runResult.data).toEqual({ latency_ms: 42, status: "succeeded" });
      await expect(
        client.storage.from("business-card-images").download(rawImagePath),
      ).resolves.toMatchObject({ data: null });
    } finally {
      await fetch(`${url}/auth/v1/admin/users/${createdUser.id}`, {
        headers: {
          apikey: serviceRoleKey,
          Authorization: `Bearer ${serviceRoleKey}`,
        },
        method: "DELETE",
      });
    }
  });
});
