import type { CardExtractionStructuredOutput } from "@miraio/domain";

type CardExtractionFixture = Readonly<{
  caseName: string;
  expectedNonNullFields: readonly string[];
  providerOutput: CardExtractionStructuredOutput;
}>;

const zeroConfidence = {
  address: 0,
  company: 0,
  department: 0,
  email: 0,
  name: 0,
  phone: 0,
  title: 0,
  website: 0,
} as const;

export const cardExtractionFixtures: readonly CardExtractionFixture[] = [
  {
    caseName: "japanese-corporate",
    expectedNonNullFields: ["name", "company", "department", "title"],
    providerOutput: {
      address: null,
      company: "ミライオ架空株式会社",
      department: "プロダクト部",
      email: null,
      field_confidence: {
        ...zeroConfidence,
        company: 0.99,
        department: 0.96,
        name: 0.98,
        title: 0.97,
      },
      language: "ja",
      name: "未来 テスト",
      phone: null,
      title: "プロダクト責任者",
      website: null,
    },
  },
  {
    caseName: "english-corporate",
    expectedNonNullFields: ["name", "company", "title", "email"],
    providerOutput: {
      address: null,
      company: "Example Invalid Labs",
      department: null,
      email: "alex.card@example.invalid",
      field_confidence: {
        ...zeroConfidence,
        company: 0.98,
        email: 0.99,
        name: 0.97,
        title: 0.96,
      },
      language: "en",
      name: "Alex Cardtest",
      phone: null,
      title: "Product Director",
      website: null,
    },
  },
  {
    caseName: "mixed-japanese-english",
    expectedNonNullFields: ["name", "company", "title", "website"],
    providerOutput: {
      address: null,
      company: "Example ミックス合同会社",
      department: null,
      email: null,
      field_confidence: {
        ...zeroConfidence,
        company: 0.95,
        name: 0.96,
        title: 0.94,
        website: 0.93,
      },
      language: "mixed",
      name: "Mira ミックス",
      phone: null,
      title: "Founder / 代表",
      website: "https://mixed.example.invalid",
    },
  },
  {
    caseName: "missing-title",
    expectedNonNullFields: ["name", "company", "department"],
    providerOutput: {
      address: null,
      company: "No Title Example",
      department: "Research",
      email: null,
      field_confidence: {
        ...zeroConfidence,
        company: 0.98,
        department: 0.92,
        name: 0.98,
      },
      language: "en",
      name: "Noa Titletest",
      phone: null,
      title: null,
      website: null,
    },
  },
  {
    caseName: "missing-department",
    expectedNonNullFields: ["name", "company", "title"],
    providerOutput: {
      address: null,
      company: "No Department Example",
      department: null,
      email: null,
      field_confidence: {
        ...zeroConfidence,
        company: 0.98,
        name: 0.98,
        title: 0.95,
      },
      language: "en",
      name: "Demi Depttest",
      phone: null,
      title: "Engineer",
      website: null,
    },
  },
  {
    caseName: "low-quality-limited",
    expectedNonNullFields: ["company"],
    providerOutput: {
      address: null,
      company: "Blur Example",
      department: "   ",
      email: null,
      field_confidence: { ...zeroConfidence, company: 0.54, department: 0.2 },
      language: "und",
      name: null,
      phone: null,
      title: null,
      website: null,
    },
  },
  {
    caseName: "sole-proprietor",
    expectedNonNullFields: ["name", "title", "email", "website"],
    providerOutput: {
      address: null,
      company: null,
      department: null,
      email: "solo.card@example.invalid",
      field_confidence: {
        ...zeroConfidence,
        email: 0.99,
        name: 0.99,
        title: 0.97,
        website: 0.98,
      },
      language: "en",
      name: "Solo Testperson",
      phone: null,
      title: "Independent Designer",
      website: "https://solo.example.invalid",
    },
  },
  {
    caseName: "website-without-email",
    expectedNonNullFields: ["company", "phone", "website"],
    providerOutput: {
      address: null,
      company: "Website Only Example",
      department: null,
      email: null,
      field_confidence: {
        ...zeroConfidence,
        company: 0.98,
        phone: 0.92,
        website: 0.99,
      },
      language: "en",
      name: null,
      phone: "+00 0000 0000 0001",
      title: null,
      website: "https://website-only.example.invalid",
    },
  },
  {
    caseName: "multiple-contact-fields",
    expectedNonNullFields: [
      "name",
      "company",
      "email",
      "phone",
      "website",
      "address",
    ],
    providerOutput: {
      address: "1 Fictional Way, Example City",
      company: "Contact Example",
      department: null,
      email: "contact.card@example.invalid",
      field_confidence: {
        ...zeroConfidence,
        address: 0.91,
        company: 0.98,
        email: 0.99,
        name: 0.98,
        phone: 0.96,
        website: 0.97,
      },
      language: "en",
      name: "Case Contacttest",
      phone: "+00 0000 0000 0002",
      title: null,
      website: "https://contact.example.invalid",
    },
  },
  {
    caseName: "minimal-name-only",
    expectedNonNullFields: ["name"],
    providerOutput: {
      address: null,
      company: null,
      department: null,
      email: null,
      field_confidence: { ...zeroConfidence, name: 0.88 },
      language: "ja",
      name: "最小 テスト",
      phone: null,
      title: null,
      website: null,
    },
  },
] as const;
